### ISSUE TITLE
Hostname validator produces notice on empty domainPart

### ISSUE THREAD

**Issue by andreasschroth** [zendframework/zend-validator#240]
Example input: `some-random-email@.com `

Notice + first call:
```
grapheme_strpos: Offset not contained in string---#0 /private/vendor/zendframework/zend-stdlib/src/StringWrapper/Intl.php(86): grapheme_strpos('', '-', 0)
#1 /private/vendor/zendframework/zend-validator/src/Hostname.php(2103): Zend\\Stdlib\\StringWrapper\\Intl->strpos('', '-')
```

**Comment by andreasschroth** [comment]
PR proposed.
